import { Catalogue } from "../interfaces/catalogue.interface";

export const catalogueMock: Catalogue = {
  _id: "",
  title: "",
  description: "",
  language: "",
  territorialScope: "",
  temporaryCoverage: "",
  updateFrequency: "",
  topic: "",
  lastUpdate: new Date(),
  format: "",
  distribution: "",
  sensitiveInformation: "",
  isUsing: "",
  accessType: "",
  internalRelationship: "",
  contactPerson: "",
  structured: "",
  associatedApplication: "",
  georeference: "",
  comments: "",
  timmingEffect: "",
  creationDate: new Date(),
  deleted: false,
  deletedDate: new Date(),
  personalData: "",
  activeAds: "",
  source: "",
  responsibleIdentity: "",
};
