export enum RESPONSIBLE_IDENTITY {
  GENERAL = "general",
  CARRERA = "Servici de Carrera i Optimització de la Gestió de Recursos Humans",
  FORMACIO = "Servici de Formació i Gestió del Coneixement",
  CENTRE_HISTORIC = "Servici Gestió del Centre Històric",
  SERTIC = "SERTIC",
  LLICENCIES_URBANISTIQUES = "Servici de Llicències Urbanístiques",
  INNOVACIO = "Servici d'Innovació",
  EMERGENCIA_CLIMATICA = "Servici d'Emergència Climàtica i Transició Energètica",
  INNOVACIO_ECONOMICA = "Servici d'Emprenedoria i Innovació Econòmica",
  DEVESA = "Servici de la Devesa-Albufera",
  PATRIMONI = "Servici de Patrimoni",
  RECURSOS_CULTURALS = "Servici de Recursos Culturals",
  AIGUA = "Servici del Cicle Integral de l'Aigua",
  SECRETARIA_GENERAL = "Servici Secretaria General",
  PLE = "Servici Secretaria General i del Ple",
  AVALUACIO_QUALITAT = "Servici d'Avaluació de Servicis i Gestió de la Qualitat",
  ASSESORAMENT_URBANISTIC = "Sevici d'Assessorament Urbanístic i programació",
  COORDINACIO_TRIBUTARIA = "Servici de Coordinació Tributaria",
  PATRIMONI_HISTORIC = "Servicio de Patrimonio Histórico",
  ACTIVITATS = "Servici d'activitats",
  INSPECCIO = "Servici d'Inspecció Municipal",
}
