export enum TOPIC {
  ciencia = "Ciencia y tecnología",
  comercio = "Comercio",
  cultura = "Cultura y ocio",
  democgrafia = "Demografía",
  deporte = "Deporte",
  economia = "Economía",
  educacion = "Educación",
  empleo = "Empleo",
  energia = "Energía",
  hacienda = "Hacienda",
  industria = "Industria",
  legislacion = "Legislación y justicia",
  medioambiente = "Medio ambiente",
  mediorural = "Medio rural",
  salud = "Salud",
  sector_publico = "Sector público",
  seguridad = "Seguridad",
  sociedad = "Sociedad y bienestar",
  transporte = "Transporte",
  turismo = "Turismo",
  urbanismo = "Urbanismo e infraestructuras",
  vivienda = "Vivienda",
}
